version: '3'
services:
    ptalk-engine:
        build:
          context: .
          args:
            COMPONENT: ptalk-engine
          dockerfile: Dockerfile
        image: rossonet/ptalk-engine:dev
        restart: unless-stopped
        ports:
            - 2045:2045
        environment:
            DEBUG: 'true'
            HAZELCAST_SERVICE: 'hazelcast'
            PTALK_SELF_ABILITY_SERVICE: 'ptalk-homunculus'
        networks:
            - ptalk-net
        depends_on:
            - hazelcast
    ptalk-channel-telegram:
        build:
          context: .
          args:
            COMPONENT: ptalk-channel-telegram
          dockerfile: Dockerfile
        image: rossonet/ptalk-channel-telegram:dev
        restart: unless-stopped
        ports:
            - 2046:2045
        environment:
            DEBUG: 'true'
            PTALK_ENGINE: 'ptalk-engine'
        networks:
            - ptalk-net
        depends_on:
            - ptalk-engine
    ptalk-channel-grpc:
        build:
          context: .
          args:
            COMPONENT: ptalk-channel-grpc
          dockerfile: Dockerfile
        image: rossonet/ptalk-channel-grpc:dev
        restart: unless-stopped
        ports:
            - 2047:2045
        environment:
            DEBUG: 'true'
            PTALK_ENGINE: 'ptalk-engine'
        networks:
            - ptalk-net
        depends_on:
            - ptalk-engine
    ptalk-channel-http:
        build:
          context: .
          args:
            COMPONENT: ptalk-channel-http
          dockerfile: Dockerfile
        image: rossonet/ptalk-channel-http:dev
        restart: unless-stopped
        ports:
            - 2048:2045
        environment:
            DEBUG: 'true'
            PTALK_ENGINE: 'ptalk-engine'
        networks:
            - ptalk-net
        depends_on:
            - ptalk-engine
    ptalk-channel-mqtt:
        build:
          context: .
          args:
            COMPONENT: ptalk-channel-mqtt
          dockerfile: Dockerfile
        image: rossonet/ptalk-channel-mqtt:dev
        restart: unless-stopped
        ports:
            - 2049:2045
        environment:
            DEBUG: 'true'
            PTALK_ENGINE: 'ptalk-engine'
        networks:
            - ptalk-net
        depends_on:
            - ptalk-engine
    ptalk-ability-homunculus:
        build:
          context: .
          args:
            COMPONENT: ptalk-ability-homunculus
          dockerfile: Dockerfile
        image: rossonet/ptalk-ability-homunculus:dev
        restart: unless-stopped
        ports:
            - 2050:2045
        environment:
            DEBUG: 'true'
            PTALK_ENGINE: 'ptalk-engine'
        networks:
            - ptalk-net
        depends_on:
            - ptalk-engine
    ptalk-ability-processmaker:
        build:
          context: .
          args:
            COMPONENT: ptalk-ability-processmaker
          dockerfile: Dockerfile
        image: rossonet/ptalk-ability-processmaker:dev
        restart: unless-stopped
        ports:
            - 2051:2045
        environment:
            DEBUG: 'true'
            PTALK_ENGINE: 'ptalk-engine'
        networks:
            - ptalk-net
        depends_on:
            - ptalk-engine
    ptalk-nlu-watson:
        build:
          context: .
          args:
            COMPONENT: ptalk-nlu-watson
          dockerfile: Dockerfile
        image: rossonet/ptalk-nlu-watson:dev
        restart: unless-stopped
        ports:
            - 2052:2045
        environment:
            DEBUG: 'true'
            PTALK_ENGINE: 'ptalk-engine'
        networks:
            - ptalk-net
        depends_on:
            - ptalk-engine
    hazelcast:
        image: hazelcast/hazelcast:5.2.2
        restart: unless-stopped
        ports:
          - 5701:5701
          - 5702:5702
        environment:
            LOGGING_LEVEL: 'INFO'
            PROMETHEUS_PORT: 5702
            HZ_NETWORK_PORT_AUTOINCREMENT: 'true'
            HZ_NETWORK_PORT_PORTCOUNT: 100
            HZ_NETWORK_PORT_PORT: 5701
            HZ_USERCODEDEPLOYMENT_ENABLED: 'true'
        networks:
            - ptalk-net

networks:
  ptalk-net:
    driver: bridge
