version: '3'
services:
    ptalk-engine:
        build:
          context: ./ptalk-engine
          dockerfile: Dockerfile
        image: rossonet/ptalk-engine:dev
        restart: unless-stopped
        ports:
            - 2045:2045'
        environment:
            DEBUG: true
            HAZELCAST_SERVICE: 'hazelcast'
            PTALK_SELF_ABILITY_SERVICE: 'ptalk-homunculus'
        networks:
            - ptalk-net
        depends_on:
            - hazelcast
    ptalk-channel-telegram:
        build:
          context: ./ptalk-channel-telegram
          dockerfile: Dockerfile
        image: rossonet/ptalk-channel-telegram:dev
        restart: unless-stopped
        ports:
            - 2045:2045'
        environment:
            DEBUG: true
            PTALK_ENGINE: 'ptalk-engine'
        networks:
            - ptalk-net
        depends_on:
            - ptalk-engine
    ptalk-channel-grpc:
        build:
          context: ./ptalk-channel-grpc
          dockerfile: Dockerfile
        image: rossonet/ptalk-channel-grpc:dev
        restart: unless-stopped
        ports:
            - 2045:2045'
        environment:
            DEBUG: true
            PTALK_ENGINE: 'ptalk-engine'
        networks:
            - ptalk-net
        depends_on:
            - ptalk-engine
    ptalk-channel-http:
        build:
          context: ./ptalk-channel-http
          dockerfile: Dockerfile
        image: rossonet/ptalk-channel-http:dev
        restart: unless-stopped
        ports:
            - 2045:2045'
        environment:
            DEBUG: true
            PTALK_ENGINE: 'ptalk-engine'
        networks:
            - ptalk-net
        depends_on:
            - ptalk-engine
    ptalk-ability-homunculus:
        build:
          context: ./ptalk-ability-homunculus
          dockerfile: Dockerfile
        image: rossonet/ptalk-ability-homunculus:dev
        restart: unless-stopped
        ports:
            - 2045:2045'
        environment:
            DEBUG: true
            PTALK_ENGINE: 'ptalk-engine'
        networks:
            - ptalk-net
        depends_on:
            - ptalk-engine
    ptalk-nlu-watson:
        build:
          context: ./ptalk-nlu-watson
          dockerfile: Dockerfile
        image: rossonet/ptalk-nlu-watson:dev
        restart: unless-stopped
        ports:
            - 2045:2045'
        environment:
            DEBUG: true
            PTALK_ENGINE: 'ptalk-engine'
        networks:
            - ptalk-net
        depends_on:
            - ptalk-engine
    hazelcast:
        image: hazelcast/hazelcast:5.2.2
        restart: unless-stopped
        ports:
          - '5701:5701'
        environment:
            LOGGING_LEVEL: DEBUG
            HZ_NETWORK_PORT_AUTOINCREMENT: true
            HZ_NETWORK_PORT_PORTCOUNT: 100
            HZ_NETWORK_PORT_PORT: 5701
        networks:
            - ptalk-net

networks:
  ptalk-net:
    driver: bridge
